export const authConstants={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILED:'LOGOUT_FAILED'
}

export const userConstants={
    USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE"
}

export const categoryConstants={
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILED:'GET_ALL_CATEGORIES_FAILED',
    ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILED:'ADD_NEW_CATEGORY_FAILED',
    UPDATE_CATEGORIES_REQUEST:'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS:'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILED:'UPDATE_CATEGORIES_FAILED',
    DELETE_CATEGORIES_REQUEST:'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS:'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILED:'DELETE_CATEGORIES_FAILED'
}

export const productConstants={
    GET_ALL_PRODUCT_REQUEST:'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS:'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILED:'GET_ALL_PRODUCT_FAILED',
    ADD_NEW_PRODUCT_REQUEST:'ADD_NEW_PRODUCT_REQUEST',
    ADD_NEW_PRODUCT_SUCCESS:'ADD_NEW_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_FAILED:'ADD_NEW_PRODUCT_FAILED'
}

export const pageConstants={
    CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILED:'CREATE_PAGE_FAILED'
}

export const orderConstants={
    GET_CUSTOMER_ORDER_REQUEST:'GET_CUSTOMER_ORDER_REQUEST',
    GET_CUSTOMER_ORDER_SUCCESS:'GET_CUSTOMER_ORDER_SUCCESS',
    GET_CUSTOMER_ORDER_FAILED:'GET_CUSTOMER_ORDER_FAILED',
    UPDATE_CUSTOMER_ORDER_REQUEST:'UPDATE_CUSTOMER_ORDER_REQUEST',
    UPDATE_CUSTOMER_ORDER_SUCCESS:'UPDATE_CUSTOMER_ORDER_SUCCESS',
    UPDATE_CUSTOMER_ORDER_FAILED:'UPDATE_CUSTOMER_ORDER_FAILED'
}